apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabricantes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabricantes
  template:
    metadata:
      labels:
        app: fabricantes
    spec:
      containers:
      - name: fabricantes
        image: gcr.io/miso-ccp-backend/fabricantes:latest
        ports:
          - containerPort: 3001
        env:
          - name: DB_NAME
            value: "fabricantes"
          - name: DB_HOST
            value: "postgres"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: USUARIOS_PATH
            value: "http://usuarios:3000"
            readinessProbe:
              httpGet:
                path: /fabricantes/ping
                port: 3000
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 2
              failureThreshold: 3
            livenessProbe:
              httpGet:
                path: /fabricantes/ping
                port: 3000
              initialDelaySeconds: 15
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: fabricantes
spec:
  selector:
    app: fabricantes
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP