apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: gcr.io/tu-proyecto/usuarios:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_NAME
              value: "usuarios"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios
spec:
  selector:
    app: usuarios
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP