packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.64.2
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.3
  zod: ^3.24.1
  "@dotenvx/dotenvx": ^1.35.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
