services:
  {{cookiecutter.project_slug}}:
    image: {{cookiecutter.project_slug}}:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=true
      - DATABASE_URL=postgresql://postgres:password@db:5432/{{cookiecutter.project_slug}}
    depends_on:
      - {{cookiecutter.project_slug}}-db
    networks:
      - {{cookiecutter.project_slug}}-net
  exp-01-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB={{cookiecutter.project_slug}}
    ports:
      - "5432:5432"
    networks:
      - {{cookiecutter.project_slug}}-net

networks:
  {{cookiecutter.project_slug}}-net:
    driver: bridge
