[project]
name = "ccp-cli"
version = "0.1.0"
description = "CLI for CCP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cookiecutter>=2.6.0",
    "rich>=13.9.4",
    "typer>=0.15.1",
]
