/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hono API
 * Greeting API
 * OpenAPI spec version: 1.0.0
 */
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'
import { useQuery } from '@tanstack/react-query'
import axios from 'axios'

import type { GetIndex200Item } from './schemas'

/**
 * Root route
 */
export const getIndex = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetIndex200Item[]>> => {
  return axios.get(`http://localhost:4000/`, options)
}

export const getGetIndexQueryKey = () => {
  return [`http://localhost:4000/`] as const
}

export const getGetIndexQueryOptions = <
  TData = Awaited<ReturnType<typeof getIndex>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData>
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetIndexQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getIndex>>> = ({
    signal,
  }) => getIndex({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getIndex>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetIndexQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIndex>>
>
export type GetIndexQueryError = AxiosError<unknown>

export function useGetIndex<
  TData = Awaited<ReturnType<typeof getIndex>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData>
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetIndexQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
