services:
  exp-01:
    image: exp-01:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=true
      - DATABASE_URL=postgresql://postgres:password@db:5432/exp-01
    depends_on:
      - exp-01-db
    networks:
      - exp-01-net
    entrypoint: [ "uv", "run", "--", "flask", "run", "--host=0.0.0.0" ]
  exp-01-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exp-01
    ports:
      - "5432:5432"
    networks:
      - exp-01-net

networks:
  exp-01-net:
    driver: bridge
