// types/roles.ts
export const ROLES = {
    ADMINISTRADOR: 'ADMINISTRADOR',
    TENDERO: 'TENDERO',
    VENDEDOR: 'VENDEDOR',
    LOGISTICA: 'LOGISTICA',
    DIRECTOR_VENTAS: 'DIRECTOR_VENTAS',
    ENCARGADO_COMPRAS_PROVEEDORES: 'ENCARGADO_COMPRAS_PROVEEDORES'
  } as const;
  
  export type UserRole = keyof typeof ROLES;