/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hono API
 * Greeting API
 * OpenAPI spec version: 1.0.0
 */
import type { GetIndex200DataItem } from './getIndex200DataItem'

export type GetIndex200 = {
  data: GetIndex200DataItem[]
}
