/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hono API
 * Greeting API
 * OpenAPI spec version: 1.0.0
 */

export * from './getIndex200'
export * from './getIndex200DataItem'
export * from './getIndex200Item'
