name: Ejecutar Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  web-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './WebApp/package-lock.json'

      - name: Install global dependencies
        run: |
          npm i -g @angular/cli

      - name: Install project dependencies
        id: install_dependencies
        run: npm ci

      - name: Run tests with coverage
        id: run_tests
        run: npm run test:coverage -- --browsers=ChromeHeadless --watch=false --no-progress

      - name: Validate if test failed
        id: result_with_error
        if: steps.run_tests.outcome == 'failure'
        env:
          MENSAJE_ERROR: Una o varias pruebas fallaron
        run: |
          echo "${MENSAJE_ERROR}"
          exit 1

      - name: Validate if test passed
        id: result_with_success
        if: steps.run_tests.outcome == 'success'
        env:
          MENSAJE_EXITO: Todas las pruebas fueron exitosas
        run: echo "${MENSAJE_EXITO}"

      - name: Approve PR
        if: steps.run_tests.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            });
            console.log('PR Review Status:', result.status);
